import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ChangeEventHandler, MouseEventHandler, useState } from "react";
import styles from "../styles/Home.module.css";
import dwn from "downloadjs";
import download from "downloadjs";
import { parse } from "path";

const Home: NextPage = () => {
  const [document, setDocument] = useState<any>();

  const uploadToClient: ChangeEventHandler<HTMLInputElement> = (event) => {
    if (event.target.files && event.target.files[0]) {
      const i = event.target.files[0];

      setDocument(i);
    }
  };

  const uploadToServer: MouseEventHandler<HTMLInputElement> = async (event) => {
    event.preventDefault();
    const body = new FormData();
    body.append("file", document);
    const response = await fetch("/api/presign", {
      method: "POST",
      body,
    });
    const fileName = parse(document.name);
    download(
      await response.blob(),
      `${fileName.name}_${new Date().toISOString()}.${fileName.ext}`
    );
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.centered}>
          <form>
            <div className={styles.fileInput}>
              <input
                title="pdf"
                type="file"
                name="pdf"
                id="pdf"
                accept="application/pdf"
                className={styles.file}
                onChange={uploadToClient}
              />
              <label htmlFor="pdf">Select file</label>
            </div>
            <div>
              {document && (
                <div className={styles.sendPanel}>
                  {document.name} - {document.size}b
                  <input
                    type="button"
                    className={styles.button}
                    onClick={uploadToServer}
                    value="Sign"
                  />
                </div>
              )}
            </div>
          </form>
        </div>
      </div>
    </>
  );
};

export default Home;
